### ISSUE TITLE
OS X test_visual_2d.py::test_visual_2d Abort trap: 6

### ISSUE THREAD

**Issue by jrcastle** [WillemEerland/teetool#2]
@WillemEerland ,

I'm in the process of reviewing your JORS submission and I cannot successfully run a test of your code.  I'm running OS X 10.11.6 and when I run your test script it aborts on test_visual_2d.py with the message Abort trap:6. I've attached the output of the py.test command.  If you need more information, please let me know.

Cheers,
James

$ py.test -v --cov-report html --cov=teetool
================================================================================ test session starts ================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/jcastle/anaconda/envs/teetool/bin/python
cachedir: ../.cache
rootdir: /Users/jcastle/Downloads/teetool-1.0, inifile:
plugins: nbval-0.5, cov-2.3.1
collected 26 items 

test_basis.py::test_basis PASSED
test_gp.py::test_cluster_data PASSED
test_gp.py::test_mix_rbf PASSED
test_gp.py::test_mix_bern PASSED
test_gp.py::test_resampling PASSED
test_gp.py::test_maximum_likelihood PASSED
test_gp.py::test_expectation_maximization PASSED
test_gp.py::test_subfunctions_EM PASSED
test_gp.py::test_subfunctions PASSED
test_helpers.py::test_ncolours PASSED
test_helpers.py::test_toy_trajectories PASSED
test_helpers.py::test_inside_hull PASSED
test_helpers.py::test_nearest_spd PASSED
test_helpers.py::test_find_nearest PASSED
test_model_1.py::test_inside PASSED
test_model_1.py::test_help_func PASSED
test_model_1.py::test_init PASSED
test_model_2.py::test_eval PASSED
test_model_3.py::test_ks PASSED
test_visual_2d.py::test_visual_2d Abort trap: 6

**Comment by WillemEerland** [comment]
Hi James,

I appreciate you contacting me on this issue directly. The problem _probably_ lies in 'matplotlib', which throws this error.

I gather this as it only occurs at visual_2d, which uses the matplotlib library, also these reports indicate a similar problem:

https://bitbucket.org/joezuntz/cosmosis/issues/43/matplotlib-abort-trap-6-with-conda

http://stackoverflow.com/questions/19827013/abort-trap-6-error-installing-pymc-on-osx-10-7

If you could add "-s" to the command

> py.test -v -s --cov-report html --cov=teetool 

that might provide more information on the exact problem with matplotlib

**Comment by jrcastle** [comment]
Hi Willem,

One quick side note, you'll want to update the test.py command in your README.md file, it's missing the double dashes for the "--cov" options.

In regards to the matplotlib, I did install that using conda specifying the version 2.0.0. I can verify this quickly by: 

>>> import matplotlib
>>> print matplotlib.__version__
2.0.0

Here's a dump of the py.test command with "-s" added:

$ py.test -v -s --cov-report html --cov=teetool
======================================================================================================= test session starts =======================================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/jcastle/anaconda/envs/teetool/bin/python
cachedir: ../.cache
rootdir: /Users/jcastle/Downloads/teetool-1.0, inifile:
plugins: nbval-0.5, cov-2.3.1
collected 26 items 

test_basis.py::test_basis PASSED
test_gp.py::test_cluster_data PASSED
test_gp.py::test_mix_rbf PASSED
test_gp.py::test_mix_bern PASSED
test_gp.py::test_resampling /Users/jcastle/anaconda/envs/teetool/lib/python2.7/site-packages/numpy/linalg/linalg.py:1502: RuntimeWarning: divide by zero encountered in true_divide
  return s[..., 0]/s[..., -1]
PASSED
test_gp.py::test_maximum_likelihood PASSED
test_gp.py::test_expectation_maximization PASSED
test_gp.py::test_subfunctions_EM PASSED
test_gp.py::test_subfunctions PASSED
test_helpers.py::test_ncolours PASSED
test_helpers.py::test_toy_trajectories PASSED
test_helpers.py::test_inside_hull PASSED
test_helpers.py::test_nearest_spd /Users/jcastle/anaconda/envs/teetool/lib/python2.7/site-packages/numpy/linalg/linalg.py:1502: RuntimeWarning: invalid value encountered in true_divide
  return s[..., 0]/s[..., -1]
PASSED
test_helpers.py::test_find_nearest PASSED
test_model_1.py::test_inside PASSED
test_model_1.py::test_help_func PASSED
test_model_1.py::test_init PASSED
test_model_2.py::test_eval PASSED
test_model_3.py::test_ks PASSED
test_visual_2d.py::test_visual_2d 2017-04-13 08:56:20.996 python[37208:4466145] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7ff9747d5d90
2017-04-13 08:56:21.002 python[37208:4466145] An uncaught exception was raised
2017-04-13 08:56:21.002 python[37208:4466145] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7ff9747d5d90
2017-04-13 08:56:21.002 python[37208:4466145] (
	0   CoreFoundation                      0x00007fff91119452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8a5d273c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9118310d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff910894d1 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff91089058 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x0000000109dc2948 TkpInit + 476
	6   Tk                                  0x0000000109d3da6e Tk_Init + 1799
	7   _tkinter.so                         0x0000000109c1ae44 Tcl_AppInit + 84
	8   _tkinter.so                         0x0000000109c15ab4 Tkinter_Create + 1140
	9   libpython2.7.dylib                  0x000000010054d1bd PyEval_EvalFrameEx + 30141
	10  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	11  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	12  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	13  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	14  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	15  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	16  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	17  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	18  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	19  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	20  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	21  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	22  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	23  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	24  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	25  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	26  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	27  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	28  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	29  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	30  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	31  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	32  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	33  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	34  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	35  libpython2.7.dylib                  0x000000010050674d slot_tp_init + 141
	36  libpython2.7.dylib                  0x0000000100502863 type_call + 339
	37  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	38  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	39  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	40  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	41  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	42  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	43  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	44  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	45  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	46  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	47  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	48  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	49  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	50  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	51  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	52  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	53  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	54  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	55  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	56  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	57  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	58  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	59  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	60  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	61  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	62  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	63  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	64  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	65  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	66  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	67  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	68  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	69  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	70  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	71  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	72  libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	73  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	74  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	75  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	76  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	77  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	78  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	79  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	80  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	81  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	82  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	83  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	84  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	85  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	86  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	87  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	88  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	89  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	90  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	91  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	92  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	93  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	94  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	95  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	96  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	97  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	98  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	99  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	100 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	101 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	102 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	103 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	104 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	105 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	106 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	107 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	108 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	109 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	110 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	111 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	112 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	113 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	114 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	115 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	116 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	117 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	118 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	119 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	120 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	121 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	122 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	123 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	124 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	125 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	126 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	127 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	128 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	129 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	130 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	131 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	132 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	133 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	134 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	135 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	136 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	137 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	138 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	139 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	140 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	141 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	142 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	143 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	144 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	145 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	146 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	147 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	148 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	149 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	150 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	151 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	152 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	153 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	154 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	155 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	156 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	157 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	158 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	159 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	160 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	161 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	162 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	163 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	164 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	165 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	166 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	167 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	168 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	169 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	170 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	171 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	172 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	173 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	174 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	175 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	176 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	177 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	178 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	179 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	180 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	181 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	182 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	183 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	184 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	185 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	186 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	187 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	188 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	189 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	190 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	191 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	192 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	193 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	194 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	195 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	196 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	197 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	198 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	199 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	200 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	201 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	202 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	203 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	204 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	205 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	206 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	207 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	208 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	209 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	210 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	211 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	212 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	213 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	214 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	215 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	216 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	217 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	218 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	219 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	220 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	221 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	222 libpython2.7.dylib                  0x00000001005452e6 PyEval_EvalCode + 54
	223 libpython2.7.dylib                  0x0000000100574254 PyRun_FileExFlags + 164
	224 libpython2.7.dylib                  0x0000000100573dd1 PyRun_SimpleFileExFlags + 769
	225 libpython2.7.dylib                  0x0000000100589a12 Py_Main + 3154
	226 python                              0x0000000100497f24 start + 52
)
2017-04-13 08:56:21.003 python[37208:4466145] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication _setup:]: unrecognized selector sent to instance 0x7ff9747d5d90'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff91119452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8a5d273c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9118310d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff910894d1 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff91089058 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x0000000109dc2948 TkpInit + 476
	6   Tk                                  0x0000000109d3da6e Tk_Init + 1799
	7   _tkinter.so                         0x0000000109c1ae44 Tcl_AppInit + 84
	8   _tkinter.so                         0x0000000109c15ab4 Tkinter_Create + 1140
	9   libpython2.7.dylib                  0x000000010054d1bd PyEval_EvalFrameEx + 30141
	10  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	11  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	12  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	13  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	14  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	15  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	16  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	17  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	18  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	19  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	20  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	21  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	22  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	23  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	24  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	25  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	26  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	27  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	28  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	29  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	30  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	31  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	32  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	33  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	34  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	35  libpython2.7.dylib                  0x000000010050674d slot_tp_init + 141
	36  libpython2.7.dylib                  0x0000000100502863 type_call + 339
	37  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	38  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	39  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	40  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	41  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	42  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	43  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	44  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	45  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	46  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	47  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	48  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	49  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	50  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	51  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	52  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	53  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	54  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	55  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	56  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	57  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	58  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	59  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	60  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	61  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	62  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	63  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	64  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	65  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	66  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	67  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	68  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	69  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	70  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	71  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	72  libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	73  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	74  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	75  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	76  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	77  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	78  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	79  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	80  libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	81  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	82  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	83  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	84  libpython2.7.dylib                  0x00000001004d043c function_call + 364
	85  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	86  libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	87  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	88  libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	89  libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	90  libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	91  libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	92  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	93  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	94  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	95  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	96  libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	97  libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	98  libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	99  libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	100 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	101 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	102 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	103 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	104 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	105 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	106 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	107 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	108 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	109 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	110 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	111 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	112 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	113 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	114 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	115 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	116 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	117 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	118 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	119 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	120 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	121 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	122 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	123 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	124 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	125 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	126 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	127 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	128 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	129 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	130 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	131 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	132 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	133 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	134 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	135 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	136 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	137 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	138 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	139 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	140 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	141 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	142 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	143 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	144 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	145 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	146 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	147 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	148 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	149 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	150 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	151 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	152 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	153 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	154 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	155 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	156 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	157 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	158 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	159 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	160 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	161 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	162 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	163 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	164 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	165 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	166 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	167 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	168 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	169 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	170 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	171 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	172 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	173 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	174 libpython2.7.dylib                  0x000000010055180d PyEval_CallObjectWithKeywords + 93
	175 libpython2.7.dylib                  0x00000001004b55c6 PyInstance_New + 134
	176 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	177 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	178 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	179 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	180 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	181 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	182 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	183 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	184 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	185 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	186 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	187 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	188 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	189 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	190 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	191 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	192 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	193 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	194 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	195 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	196 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	197 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	198 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	199 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	200 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	201 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	202 libpython2.7.dylib                  0x000000010054d901 PyEval_EvalFrameEx + 32001
	203 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	204 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	205 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	206 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	207 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	208 libpython2.7.dylib                  0x00000001005520b2 fast_function + 274
	209 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	210 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	211 libpython2.7.dylib                  0x00000001004d043c function_call + 364
	212 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	213 libpython2.7.dylib                  0x00000001004b75b6 instancemethod_call + 182
	214 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	215 libpython2.7.dylib                  0x00000001005057e5 slot_tp_call + 133
	216 libpython2.7.dylib                  0x00000001004aa333 PyObject_Call + 99
	217 libpython2.7.dylib                  0x000000010054ce8f PyEval_EvalFrameEx + 29327
	218 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	219 libpython2.7.dylib                  0x0000000100552015 fast_function + 117
	220 libpython2.7.dylib                  0x000000010054cdb3 PyEval_EvalFrameEx + 29107
	221 libpython2.7.dylib                  0x00000001005458f2 PyEval_EvalCodeEx + 1538
	222 libpython2.7.dylib                  0x00000001005452e6 PyEval_EvalCode + 54
	223 libpython2.7.dylib                  0x0000000100574254 PyRun_FileExFlags + 164
	224 libpython2.7.dylib                  0x0000000100573dd1 PyRun_SimpleFileExFlags + 769
	225 libpython2.7.dylib                  0x0000000100589a12 Py_Main + 3154
	226 python                              0x0000000100497f24 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by WillemEerland** [comment]
When I try the following procedure on OSX, it works on the macbook pro:

> conda create -n teetool python=2.7 pytest pytest-cov mayavi numpy scipy

> source activate teetool

> conda install matplotlib

> pip install .

> (cd test ; py.test -v --cov-report html --cov=teetool)

however, this installs an earlier version of matplotlib, but with the modifications this doesn't cause problems.

> import matplotlib
> print matplotlib.\_\_version__
> 1.5.1

You might have to remove your conda environment

> conda remove -n teetool --all

and start fresh, especially as the 

> pip install matplotlib

does actually install matplotlib, but my experience is that this doesn't install the backends required, therefore throwing errors.

I have updated the README.md in the repository and will be included in the next stable version.

**Comment by jrcastle** [comment]
I've repeated the procedure, starting fresh, and the test step still fails at test_visual_2d with the same error.  The version of Matplotlib in this case is now 1.5.1 (I've also attempted 1.5.3 with the same result).  It's strange that this is working on your system, but not mine.

**Comment by WillemEerland** [comment]
Thanks to the unit tests being checked via Travis CI, I am certain there are no problems with the package on Ubuntu.

There is a fix, which looks promising:

https://github.com/MTG/sms-tools/issues/33

which basically involves selecting the backend "TkAgg", specifically for OSX:

> import matplotlib
> matplotlib.use("TkAgg")

**Comment by jrcastle** [comment]
I've come across a similar proposed fix that involves adding
>backend: TkAgg
in ~/.matplotlib/matplotlibrc

If the two approaches are equivalent, then this doesn't help the situation.  In which file should I place your proposed fix?

**Comment by WillemEerland** [comment]
in the file __visual\_2d.py__ , insert 

> import matplotlib
> matplotlib.use("TkAgg")

above 

> import matplotlib.pyplot as plt

resulting in the following imports in __visual\_2d.py__

> import numpy as np
> from scipy.interpolate import griddata
> import matplotlib
> matplotlib.use("TkAgg")
> import matplotlib.pyplot as plt
> import teetool as tt

I am uncertain whether these two approaches are equivalent, as conda might use a matplotlib library elsewhere.

Finally, you might want to try other backends, "Agg" and "macosx" both work for me, found at: 

https://matplotlib.org/faq/usage_faq.html#what-is-a-backend

**Comment by jrcastle** [comment]
It's working now, and I believe I've isolated the issue.  I had multiple implementations of classes tied to the TkAgg backend, which is a common issue with anacondas and OS X (https://github.com/WillemEerland/teetool/issues/2):

>objc[41294]: Class TKApplication is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/jcastle/anaconda/envs/teetool/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
>objc[41294]: Class TKMenu is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/jcastle/anaconda/envs/teetool/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
>objc[41294]: Class TKContentView is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/jcastle/anaconda/envs/teetool/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.
>objc[41294]: Class TKWindow is implemented in both /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk and /Users/jcastle/anaconda/envs/teetool/lib/libtk8.5.dylib. One of the two will be used. Which one is undefined.

As you have suggested, using a different backend fixes the problem and the reason why the errors are recurring is that apparently the ~/.matplotlib/matplotlibrc always wins and adding in lines like 

>import matplotlib
>matplotlib.use("Agg")

doesn't do anything when ~/.matplotlib/matplotlibrc has

>backend: TkAgg

Therefore, by _actually_  changing the backend to Agg,  the issue is resolved and tests now pass:

$ py.test -v --cov-report html --cov=teetool
======================================================================================================= test session starts =======================================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/jcastle/anaconda/envs/teetool/bin/python
cachedir: ../.cache
rootdir: /Users/jcastle/Downloads/teetool-1.0, inifile:
plugins: cov-2.3.1
collected 26 items 

test_basis.py::test_basis PASSED
test_gp.py::test_cluster_data PASSED
test_gp.py::test_mix_rbf PASSED
test_gp.py::test_mix_bern PASSED
test_gp.py::test_resampling PASSED
test_gp.py::test_maximum_likelihood PASSED
test_gp.py::test_expectation_maximization PASSED
test_gp.py::test_subfunctions_EM PASSED
test_gp.py::test_subfunctions PASSED
test_helpers.py::test_ncolours PASSED
test_helpers.py::test_toy_trajectories PASSED
test_helpers.py::test_inside_hull PASSED
test_helpers.py::test_nearest_spd PASSED
test_helpers.py::test_find_nearest PASSED
test_model_1.py::test_inside PASSED
test_model_1.py::test_help_func PASSED
test_model_1.py::test_init PASSED
test_model_2.py::test_eval PASSED
test_model_3.py::test_ks PASSED
test_visual_2d.py::test_visual_2d PASSED
test_visual_2d.py::test_subplots PASSED
test_visual_3d.py::test_visual_3d PASSED
test_world.py::test_init PASSED
test_world.py::test_addCluster PASSED
test_world.py::test_model PASSED
test_world.py::test_data_point PASSED

---------- coverage: platform darwin, python 2.7.13-final-0 ----------
Coverage HTML written to dir htmlcov


=================================================================================================== 26 passed in 40.85 seconds ====================================================================================================

**Comment by WillemEerland** [comment]
Ah, I didn't realise **~/.matplotlib/matplotlibrc** overrules, good to know.

Glad it's resolved!
